# Generated by Django 4.0.3 on 2022-04-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_game_category_games_games_authors_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['publish_date', 'title'], 'verbose_name': 'Видеоигры', 'verbose_name_plural': 'Видеоигры'},
        ),
        migrations.AlterModelOptions(
            name='games_authors',
            options={'ordering': ['id', 'company'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='gamestore_games',
            options={'ordering': ['price', 'count'], 'verbose_name': 'Игры в магазинах', 'verbose_name_plural': 'Игры в магазинах'},
        ),
        migrations.AlterModelOptions(
            name='gamestore_sold_games',
            options={'ordering': ['price', 'insert_date'], 'verbose_name': 'Проданные игры', 'verbose_name_plural': 'Проданные игры'},
        ),
        migrations.AlterModelOptions(
            name='gamestores',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Магазин видеоигр', 'verbose_name_plural': 'Магазины Видеоигр'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['login'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='games',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='game_category',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='games',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.games_authors', verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='games',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.game_category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='games',
            name='publish_date',
            field=models.DateField(auto_now_add=True, verbose_name='публикация'),
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='gamestore_games',
            name='count',
            field=models.IntegerField(verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='gamestore_games',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='gamestore_sold_games',
            name='insert_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='gamestore_sold_games',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='gamestore_sold_games',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='gamestores',
            name='name',
            field=models.CharField(max_length=100, verbose_name='навзвание'),
        ),
        migrations.AlterField(
            model_name='gamestores',
            name='web_site',
            field=models.CharField(max_length=100, verbose_name='веб-сайт'),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=40, verbose_name='имя пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=40, verbose_name='пароль'),
        ),
    ]
