# Generated by Django 4.0.3 on 2022-05-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_category_game_category_name_games_favourites_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gamestore_sold_games',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
